[package]
name = "bittorrent_client"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
reqwest = "0.12.9"
tokio = { version = "1.42.0", features = ["io-util", "macros", "net", "sync"] }

[dev-dependencies]
mockito = "1.6.1"
tokio-test = "0.4.4"
