[package]
name = "bittorrent_client"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
tokio = { version = "1.42.0", features = ["io-util", "macros", "net"] }

[dev-dependencies]
tokio-test = "0.4.4"
